apiVersion: v1
kind: Service
metadata:
  name: {{ include "vueapp-chart-project.fullname" . }}
  labels:
    {{- include "vueapp-chart-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}   #NodePort
  ports:
    - port: {{ .Values.service.port }}    #80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "vueapp-chart-project.selectorLabels" . | nindent 4 }}
